version: 2.1

jobs:
  unittests-py313:
    docker:
      - image: python:3.13.6-bullseye
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - run: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: pytest tests/unittests --verbose --full-trace
  unittests-py311:
    docker:
      - image: python:3.11.3-bullseye
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - run: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: pytest tests/unittests --verbose --full-trace
  integrationtests-py313:
    docker:
      - image: python:3.13.6-bullseye
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - run: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: pytest tests/integrationtests --verbose --full-trace
  integrationtests-py311:
    docker:
      - image: python:3.11.3-bullseye
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - run: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: pytest tests/integrationtests --verbose --full-trace
  e2etests-chrome112-py311:
    docker:
      - image: matseymour/chrome-python:112.0.5615.121-3.11.3
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - run: git config --global url."https://github.com/".insteadOf "git@github.com:"
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: tini -s -- xvfb-run pytest tests/e2etests --verbose --full-trace
workflows:
  test:
    jobs:
      - unittests-py313
      - unittests-py311
      - integrationtests-py313
      - integrationtests-py311
      - e2etests-chrome112-py311
