version: 2.1

jobs:
  unittests-py38:
    docker:
      - image: python:3.8.16-bullseye
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: pytest tests/unittests --verbose --full-trace
  unittests-py311:
    docker:
      - image: python:3.11.3-bullseye
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: pytest tests/unittests --verbose --full-trace
  integrationtests-py38:
    docker:
      - image: python:3.8.16-bullseye
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: pytest tests/integrationtests --verbose --full-trace
  integrationtests-py311:
    docker:
      - image: python:3.11.3-bullseye
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: pytest tests/integrationtests --verbose --full-trace
  e2etests-chrome106-py38:
    docker:
      - image: matseymour/chrome-python:106.0.5249.61-3.8.16
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: tini -s -- xvfb-run pytest tests/e2etests --verbose --full-trace
  e2etests-chrome112-py311:
    docker:
      - image: matseymour/chrome-python:112.0.5615.121-3.11.3
    steps:
      - run: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - checkout
      - run: pip install -r dev_requirements.txt
      - run: tini -s -- xvfb-run pytest tests/e2etests --verbose --full-trace
workflows:
  test:
    jobs:
      - unittests-py38
      - unittests-py311
      - integrationtests-py38
      - integrationtests-py311
      - e2etests-chrome106-py38
      - e2etests-chrome112-py311
